import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

// Translation data
const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Hero Section
    'hero.badge': '🚀 Leading IT Solutions Provider',
    'hero.title': 'Empowering Your',
    'hero.titleHighlight': 'Business with Technology',
    'hero.subtitle': 'Transform your business with cutting-edge technology solutions. We provide comprehensive IT services to help you stay ahead in the digital era.',
    'hero.cta': 'Start Your Project',
    'hero.watchDemo': 'Watch Demo',
    'hero.stats.projects': 'Projects Completed',
    'hero.stats.clients': 'Happy Clients',
    'hero.stats.experience': 'Years Experience',
    'hero.stats.satisfaction': 'Satisfaction Rate',

    // About Section
    // Statistics Section
    'statistics.title': 'Our Achievements',
    'statistics.description': 'Numbers that prove our dedication and quality of service in delivering the best technology solutions.',

    'about.badge': '💼 About EzProject',
    'about.title': 'Innovative Solutions for',
    'about.titleHighlight': 'Modern Businesses',
    'about.description': 'With over 10 years of experience in the technology industry, EzProject has been a trusted partner for businesses looking to leverage technology for growth and efficiency.',
    'about.description1': 'We are a leading technology solutions provider committed to helping businesses achieve digital transformation through innovative and reliable solutions.',
    'about.description2': 'Our experienced team is ready to help you leverage the latest technology to improve efficiency, productivity, and competitiveness in the digital market.',
    'about.whyChooseUs.title': 'Why Choose EzProject?',
    'about.whyChooseUs.subtitle': 'We provide comprehensive technology solutions with a professional approach and guaranteed quality results.',
    'about.experience': 'Years Experience',
    'about.projects': 'Projects Completed',
    'about.clients': 'Happy Clients',
    'about.awards': 'Awards Won',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To provide innovative and reliable technology solutions that help businesses achieve their goals and stay competitive in the digital era.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'To become the leading technology solutions provider in the region, recognized for excellence, innovation, and customer satisfaction.',
    'about.whyChoose.title': 'Why Choose Us?',
    'about.advantages.expert.title': 'Expert Team',
    'about.advantages.expert.description': 'Our team consists of certified professionals with extensive experience in various technology fields.',
    'about.advantages.technology.title': 'Leading Technology',
    'about.advantages.technology.description': 'We use the latest and most reliable technologies to ensure optimal solutions for your business.',
    'about.advantages.support.title': '24/7 Support',
    'about.advantages.support.description': 'Our technical support team is ready to help you anytime, anywhere.',
    'about.advantages.pricing.title': 'Competitive Pricing',
    'about.advantages.pricing.description': 'We offer transparent and competitive pricing without compromising on quality.',

    // Why Choose Us Section
    'whyChoose.title': 'Why Choose',
    'whyChoose.description': 'We are committed to providing the best technology solutions with a professional approach and results that exceed expectations.',
    'whyChoose.security.title': 'Guaranteed Security',
    'whyChoose.security.description': 'Implementation of high security standards with encryption and leading security protocols to protect your business data.',
    'whyChoose.performance.title': 'High Performance',
    'whyChoose.performance.description': 'Maximum performance optimization with caching technology and CDN to ensure applications run fast and responsive.',
    'whyChoose.expert.title': 'Expert Team',
    'whyChoose.expert.description': 'Experienced development team with international certifications and expertise in various modern technologies.',
    'whyChoose.quality.title': 'Premium Quality',
    'whyChoose.quality.description': 'High quality standards with comprehensive testing and quality assurance to ensure perfect results.',
    'whyChoose.onTime.title': 'On Time',
    'whyChoose.onTime.description': 'Commitment to completing projects according to agreed timelines with structured project management.',
    'whyChoose.support.title': '24/7 Support',
    'whyChoose.support.description': 'Continuous support services with fast response times to ensure systems always run optimally.',

    // Services Section
    'services.badge': '🛠️ Our Services',
    'services.title': 'Professional',
    'services.titleHighlight': 'Services',
    'services.titleSuffix': 'We Offer',
    'services.subtitle': 'We provide comprehensive technology services to support your business growth and digital transformation.',
    'services.website.title': 'Website Development',
    'services.website.description': 'Responsive and modern websites with cutting-edge technology to enhance your business online presence.',
    'services.website.features.responsive': 'Responsive Design',
    'services.website.features.seo': 'SEO Optimized',
    'services.website.features.fast': 'Fast Loading',
    'services.website.features.secure': 'Secure & Reliable',
    'services.app.title': 'Application Development',
    'services.app.description': 'User-friendly mobile and desktop applications with high performance for all platforms.',
    'services.app.features.crossPlatform': 'Cross Platform',
    'services.app.features.performance': 'Native Performance',
    'services.app.features.ui': 'Intuitive UI/UX',
    'services.app.features.cloud': 'Cloud Integration',
    'services.integration.title': 'System Integration',
    'services.integration.description': 'Integrating various business systems to improve operational efficiency and productivity.',
    'services.integration.features.api': 'API Integration',
    'services.integration.features.sync': 'Data Synchronization',
    'services.integration.features.automation': 'Workflow Automation',
    'services.integration.features.monitoring': 'Real-time Monitoring',
    'services.consulting.title': 'IT Consulting',
    'services.consulting.description': 'Strategic consulting for digital transformation and optimization of corporate technology infrastructure.',
    'services.consulting.features.strategy': 'Digital Strategy',
    'services.consulting.features.audit': 'Technology Audit',
    'services.consulting.features.planning': 'Infrastructure Planning',
    'services.consulting.features.training': 'Team Training',
    'services.learnMore': 'Learn More',
    'services.cta.title': 'Ready for Digital Transformation?',
    'services.cta.description': 'Let\'s discuss how we can help develop the right technology solutions for your business needs.',
    'services.cta.consultation': 'Free Consultation',
    'services.carousel.user': 'Users of the products, services, and features',

    // Portfolio Section
    'portfolio.badge': '🎯 Our Work',
    'portfolio.title': 'Our Latest',
    'portfolio.titleHighlight': 'Portfolio',
    'portfolio.titleSuffix': '',
    'portfolio.subtitle': 'See various projects we have completed with cutting-edge technology and high quality standards.',
    'portfolio.viewAll': 'View All Portfolio',
    'portfolio.projects.migration.title': 'Migration Database DB2 to Oracle',
    'portfolio.projects.migration.category': 'Migration',
    'portfolio.projects.migration.description': 'Successfully migrated legacy database system from DB2 to Oracle while maintaining data integrity.',
    'portfolio.projects.bprmaa.title': 'Company Profile BPR MAA',
    'portfolio.projects.bprmaa.category': 'Web Development',
    'portfolio.projects.bprmaa.description': 'Modern and responsive company website showcasing BPR MAA services, history, and corporate information.',
    'portfolio.projects.bprmaainternal.title': 'BPR MAA Internal System',
    'portfolio.projects.bprmaainternal.category': 'Web Development',
    'portfolio.projects.bprmaainternal.description': 'Internal portal for BPR MAA employees, providing access to company resources and information.',
    'portfolio.projects.taskmanagement.title': 'Task Management BPR MAA',
    'portfolio.projects.taskmanagement.category': 'Web Development',
    'portfolio.projects.taskmanagement.description': 'Project and task management system to track and organize work assignments within BPR MAA.',
    'portfolio.projects.stock.title': 'Stock Asset BPR MAA',
    'portfolio.projects.stock.category': 'Web Development',
    'portfolio.projects.stock.description': 'Stock Asset BPR MAA',
    'portfolio.projects.lelang.title': 'Lelang BPR MAA',
    'portfolio.projects.lelang.category': 'Web Development',
    'portfolio.projects.lelang.description': 'Online auction platform for BPR MAA asset disposal and management.',
    'portfolio.projects.zimbra.title': 'Zimbra Email System',
    'portfolio.projects.zimbra.category': 'Web Development',
    'portfolio.projects.zimbra.description': 'Zimbra email system for BPR MAA employees, providing secure and efficient email communication.',
    'portfolio.projects.filesharing.title': 'File Sharing BPR MAA',
    'portfolio.projects.filesharing.category': 'Web Development',
    'portfolio.projects.filesharing.description': 'File sharing system for BPR MAA employees, providing secure and efficient file sharing.',
    'portfolio.projects.recruitment.title': 'Recruitment BPR MAA',
    'portfolio.projects.recruitment.category': 'Web Development',
    'portfolio.projects.recruitment.description': 'Recruitment system for BPR MAA, providing a seamless and efficient recruitment process.',
    'portfolio.projects.disabilities.title': 'Disabilities BPR MAA',
    'portfolio.projects.disabilities.category': 'Mobile Development',
    'portfolio.projects.disabilities.description': 'Disabilities system for BPR MAA, providing a seamless and efficient disabilities process.',
    'portfolio.projects.smk.title': 'SMK 1 Sragi',
    'portfolio.projects.smk.category': 'Web Development',
    'portfolio.projects.smk.description': 'Professional company profile website for SMK 1 Sragi showcasing academic programs, student achievements, facilities, and school activities to highlight their educational excellence.',
    'portfolio.projects.roman.title': 'Roman Furniture',
    'portfolio.projects.roman.category': 'Web Development',
    'portfolio.projects.roman.description': 'Company profile website for Roman Furniture showcasing their premium furniture collections, custom design services, and showroom locations.',
    'portfolio.projects.roma.title': 'Roma Bangunan',
    'portfolio.projects.roma.category': 'Web Development',
    'portfolio.projects.roma.description': 'Company profile website for Roma Bangunan showcasing their building materials catalog, construction supplies, and multiple store locations.',
    'portfolio.projects.kpi.title': 'KPI Online BPR MAA',
    'portfolio.projects.kpi.category': 'Web Development',
    'portfolio.projects.kpi.description': 'Online key performance indicator system for BPR MAA employees, providing real-time performance tracking and analysis.',
    'portfolio.projects.leave.title': 'Leave Application BPR MAA',
    'portfolio.projects.leave.category': 'Web Development',
    'portfolio.projects.leave.description': 'Leave application system for BPR MAA employees, providing a seamless and efficient leave process.',
    'portfolio.projects.sijitu.title': 'Accuris Face Recognition System',
    'portfolio.projects.sijitu.category': 'Artificial Intelligence',
    'portfolio.projects.sijitu.description': 'SIJITU is an AI-powered anti-money laundering application designed to help institutions verify identities and detect suspicious activities. One of its core features is facial recognition, which enables accurate and automated identity verification. The system is ideal for financial compliance, risk monitoring, and secure onboarding processes.',
    'portfolio.projects.kosman.title': 'Kosman - Rental Management System',
    'portfolio.projects.kosman.category': 'Web Development',
    'portfolio.projects.kosman.description': 'Kosman is a web application designed to manage rental properties efficiently. It provides features for property listings, tenant management, and payment tracking, making it easier for landlords to oversee their rental business. The platform is user-friendly and integrates modern web technologies to ensure a smooth user experience.',
    'portfolio.projects.barbershop.title': 'Barbershop Management System',
    'portfolio.projects.barbershop.category': 'Web Development',
    'portfolio.projects.barbershop.description': 'Barbershop is a web application designed to streamline barbershop operations. It includes features for appointment scheduling, customer management, and service tracking, allowing barbershops to enhance their service delivery and customer satisfaction. The system is built with modern web technologies to ensure reliability and ease of use.',

    // Testimonials Section
    'testimonials.title': 'Client',
    'testimonials.titleHighlight': 'Testimonials',
    'testimonials.titleSuffix': 'We Serve',
    'testimonials.description': 'Hear directly from clients who have experienced the benefits of technology solutions from EzProject.',

    // Footer Section
    'footer.description': 'Empowering businesses with cutting-edge technology solutions. We are committed to delivering digital innovations that drive your business growth and transformation.',
    'footer.followUs': 'Follow Us',
    'footer.quickContact': 'Quick Contact',
    'footer.copyright': '© 2024 EzProject. All rights reserved.',
    'footer.sections.services': 'Services',
    'footer.sections.company': 'Company',
    'footer.sections.resources': 'Resources',
    'footer.sections.newsletter': 'Newsletter',
    'footer.newsletter.description': 'Get the latest updates on technology and digital tips.',
    'footer.newsletter.placeholder': 'Your Email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.services.website': 'Website Development',
    'footer.services.mobile': 'Mobile Apps',
    'footer.services.desktop': 'Desktop Apps',
    'footer.services.integration': 'System Integration',
    'footer.services.consulting': 'IT Consulting',
    'footer.services.iot': 'Internet Of Things Product',
    'footer.services.ai': 'Artificial Intelligence system',
    'footer.company.about': 'About Us',
    'footer.company.team': 'Team',
    'footer.company.career': 'Career',
    'footer.company.blog': 'Blog',
    'footer.company.contact': 'Contact',
    'footer.resources.portfolio': 'Portfolio',
    'footer.resources.caseStudies': 'Case Studies',
    'footer.resources.documentation': 'Documentation',
    'footer.resources.support': 'Support',
    'footer.resources.faq': 'FAQ',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookie': 'Cookie Policy',
    'footer.legal.sla': 'SLA Agreement',

    // Service Detail Section
    'serviceDetail.website.title': 'Website Development',
    'serviceDetail.website.subtitle': 'Professional Website Solutions for Modern Business',
    'serviceDetail.website.description': 'We develop responsive and modern websites with cutting-edge technology to enhance your business online presence. From landing pages to complex e-commerce, we are ready to help realize your digital vision.',
    'serviceDetail.website.features.responsive': 'Responsive Design',
    'serviceDetail.website.features.seo': 'SEO Optimized',
    'serviceDetail.website.features.fast': 'Fast Loading',
    'serviceDetail.website.features.secure': 'Secure & Reliable',
    'serviceDetail.website.features.cms': 'Content Management System',
    'serviceDetail.website.features.ecommerce': 'E-commerce Integration',
    'serviceDetail.website.features.analytics': 'Analytics Integration',
    'serviceDetail.website.features.social': 'Social Media Integration',
    'serviceDetail.website.benefits.credibility': 'Increase business credibility',
    'serviceDetail.website.benefits.reach': 'Wider market reach',
    'serviceDetail.website.benefits.automation': 'Business process automation',
    'serviceDetail.website.benefits.analytics': 'Real-time performance analysis',
    'serviceDetail.website.process.consultation': 'Consultation & Needs Analysis',
    'serviceDetail.website.process.design': 'UI/UX Design',
    'serviceDetail.website.process.development': 'Development & Testing',
    'serviceDetail.website.process.launch': 'Launch & Maintenance',
    'serviceDetail.website.pricing': 'Starting from $3,500',
    'serviceDetail.website.timeline': '2-6 weeks',
    'serviceDetail.app.title': 'Application Development',
    'serviceDetail.app.subtitle': 'Powerful Mobile & Desktop Applications',
    'serviceDetail.app.description': 'We develop user-friendly mobile and desktop applications with high performance for all platforms. From native mobile apps to cross-platform solutions, we create applications that provide optimal user experience.',

    // Contact Section
    'contact.map.title': 'Our Location',
    'contact.map.button': 'View on Google Maps',
    'contact.form.buttons.send': 'Send Message',
    'contact.form.buttons.sending': 'Sending...',
    'contact.form.errors.connectionError': 'Connection error. Please try again later.',
    'contact.services.desktop': 'Desktop Applications',
    'contact.services.integration': 'System Integration',

    // Contact Section
    'contact.badge': '📞 Get In Touch',
    'contact.title': 'Contact',
    'contact.titleHighlight': 'Us',
    'contact.subtitle': 'Ready to start your technology project? Contact us for a free consultation and discuss your business needs.',
    'contact.info.title': 'Contact Information',
    'contact.info.address.title': 'Our Address',
    'contact.info.address.description': 'Jl. Teknologi No. 123, Jakarta Selatan 12345',
    'contact.info.phone.title': 'Phone',
    // 'contact.info.phone.description': '+62 21 1234 5678',
    'contact.info.email.title': 'Email',
    'contact.info.email.description': 'cs@ezproject.tech',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.description': 'Monday - Friday: 09:00 - 18:00',
    'contact.services.website': 'Website Development',
    'contact.services.mobile': 'Mobile App Development',
    'contact.services.system': 'System Integration',
    'contact.services.consulting': 'IT Consulting',
    'contact.services.maintenance': 'System Maintenance',
    'contact.services.iot': 'Internet Of Things Product',
    'contact.services.ai': 'Artificial Intelligence System',
    'contact.services.other': 'Other Services',
    'contact.chat.title': 'Live Chat',
    'contact.chat.description': 'Need immediate help? Chat with our support team.',
    'contact.chat.button': 'Start Chat',
    'contact.chat.whatsappMessage': 'Hello, I need information about EzProject services.',
    'contact.hours.title': 'Business Hours',
    'contact.hours.monday': 'Monday',
    'contact.hours.tuesday': 'Tuesday',
    'contact.hours.wednesday': 'Wednesday',
    'contact.hours.thursday': 'Thursday',
    'contact.hours.friday': 'Friday',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.weekdays': 'Monday - Friday',
    'contact.hours.closed': 'Closed',
    'contact.form.title': 'Free Consultation',
    'contact.form.name': 'Full Name',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Enter your email address',
    'contact.form.company': 'Company',
    'contact.form.companyPlaceholder': 'Enter your company name',
    'contact.form.phone': 'Phone Number',
    'contact.form.phonePlaceholder': 'Enter your phone number',
    'contact.form.service': 'Service Needed',
    'contact.form.servicePlaceholder': 'Select the service you need',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Describe your project or needs',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Thank you! Your consultation request has been sent successfully.',
    'contact.form.error': 'Sorry, there was an error sending your message. Please try again.',
    'contact.form.serverError': 'Server connection error. Please try again later.',
    'contact.location.title': 'Office Location',
    'contact.location.viewMap': 'View on Google Maps',

  },
  id: {
    // Navbar
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.services': 'Layanan',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Kontak',
    'nav.getStarted': 'Mulai Sekarang',

    // Hero Section
    'hero.badge': '🚀 Penyedia Solusi IT Terdepan',
    'hero.title': 'Memberdayakan',
    'hero.titleHighlight': 'Bisnis Anda dengan Teknologi',
    'hero.subtitle': 'Transformasikan bisnis Anda dengan solusi teknologi terdepan. Kami menyediakan layanan IT komprehensif untuk membantu Anda tetap unggul di era digital.',
    'hero.cta': 'Mulai Proyek Anda',
    'hero.watchDemo': 'Lihat Demo',
    'hero.stats.projects': 'Proyek Selesai',
    'hero.stats.clients': 'Klien Puas',
    'hero.stats.experience': 'Tahun Pengalaman',
    'hero.stats.satisfaction': 'Tingkat Kepuasan',

    // About Section
    // Statistics Section
    'statistics.title': 'Pencapaian Kami',
    'statistics.description': 'Angka-angka yang membuktikan dedikasi dan kualitas layanan kami dalam menghadirkan solusi teknologi terbaik.',

    'about.badge': '💼 Tentang EzProject',
    'about.title': 'Solusi Inovatif untuk',
    'about.titleHighlight': 'Bisnis Modern',
    'about.description': 'Dengan pengalaman lebih dari 10 tahun di industri teknologi, EzProject telah menjadi mitra terpercaya bagi bisnis yang ingin memanfaatkan teknologi untuk pertumbuhan dan efisiensi.',
    'about.description1': 'Kami adalah penyedia solusi teknologi terdepan yang berkomitmen membantu bisnis mencapai transformasi digital melalui solusi yang inovatif dan terpercaya.',
    'about.description2': 'Tim berpengalaman kami siap membantu Anda memanfaatkan teknologi terkini untuk meningkatkan efisiensi, produktivitas, dan daya saing di pasar digital.',
    'about.whyChooseUs.title': 'Mengapa Memilih EzProject?',
    'about.whyChooseUs.subtitle': 'Kami menyediakan solusi teknologi komprehensif dengan pendekatan profesional dan hasil berkualitas terjamin.',
    'about.experience': 'Tahun Pengalaman',
    'about.projects': 'Proyek Selesai',
    'about.clients': 'Klien Puas',
    'about.awards': 'Penghargaan',
    'about.mission.title': 'Misi Kami',
    'about.mission.description': 'Menyediakan solusi teknologi yang inovatif dan terpercaya untuk membantu bisnis mencapai tujuan mereka dan tetap kompetitif di era digital.',
    'about.vision.title': 'Visi Kami',
    'about.vision.description': 'Menjadi penyedia solusi teknologi terdepan di kawasan, diakui karena keunggulan, inovasi, dan kepuasan pelanggan.',
    'about.whyChoose.title': 'Mengapa Memilih Kami?',
    'about.advantages.expert.title': 'Tim Expert Berpengalaman',
    'about.advantages.expert.description': 'Tim kami terdiri dari profesional bersertifikat dengan pengalaman luas di berbagai bidang teknologi.',
    'about.advantages.technology.title': 'Teknologi Terdepan',
    'about.advantages.technology.description': 'Kami menggunakan teknologi terbaru dan paling terpercaya untuk memastikan solusi optimal bagi bisnis Anda.',
    'about.advantages.support.title': 'Dukungan 24/7',
    'about.advantages.support.description': 'Tim dukungan teknis kami siap membantu Anda kapan saja, di mana saja.',
    'about.advantages.pricing.title': 'Harga Kompetitif',
    'about.advantages.pricing.description': 'Kami menawarkan harga yang transparan dan kompetitif tanpa mengorbankan kualitas.',

    // Why Choose Us Section
    'whyChoose.title': 'Mengapa Memilih',
    'whyChoose.description': 'Kami berkomitmen memberikan solusi teknologi terbaik dengan pendekatan yang profesional dan hasil yang melampaui ekspektasi.',
    'whyChoose.security.title': 'Keamanan Terjamin',
    'whyChoose.security.description': 'Implementasi standar keamanan tinggi dengan enkripsi dan protokol keamanan terdepan untuk melindungi data bisnis Anda.',
    'whyChoose.performance.title': 'Performa Tinggi',
    'whyChoose.performance.description': 'Optimisasi performa maksimal dengan teknologi caching dan CDN untuk memastikan aplikasi berjalan cepat dan responsif.',
    'whyChoose.expert.title': 'Tim Expert',
    'whyChoose.expert.description': 'Tim developer berpengalaman dengan sertifikasi internasional dan expertise di berbagai teknologi modern.',
    'whyChoose.quality.title': 'Kualitas Premium',
    'whyChoose.quality.description': 'Standar kualitas tinggi dengan testing menyeluruh dan quality assurance untuk memastikan hasil yang sempurna.',
    'whyChoose.onTime.title': 'Tepat Waktu',
    'whyChoose.onTime.description': 'Komitmen menyelesaikan proyek sesuai timeline yang disepakati dengan project management yang terstruktur.',
    'whyChoose.support.title': 'Support 24/7',
    'whyChoose.support.description': 'Layanan support berkelanjutan dengan response time cepat untuk memastikan sistem selalu berjalan optimal.',

    // Services Section
    'services.badge': '🛠️ Layanan Kami',
    'services.title': 'Layanan',
    'services.titleHighlight': 'Profesional',
    'services.titleSuffix': 'Kami',
    'services.subtitle': 'Kami menyediakan berbagai layanan teknologi komprehensif untuk mendukung pertumbuhan dan transformasi digital bisnis Anda.',
    'services.website.title': 'Pembuatan Website',
    'services.website.description': 'Website responsif dan modern dengan teknologi terdepan untuk meningkatkan presence online bisnis Anda.',
    'services.website.features.responsive': 'Responsive Design',
    'services.website.features.seo': 'SEO Optimized',
    'services.website.features.fast': 'Fast Loading',
    'services.website.features.secure': 'Secure & Reliable',
    'services.app.title': 'Pengembangan Aplikasi',
    'services.app.description': 'Aplikasi mobile dan desktop yang user-friendly dengan performa tinggi untuk semua platform.',
    'services.app.features.crossPlatform': 'Cross Platform',
    'services.app.features.performance': 'Native Performance',
    'services.app.features.ui': 'Intuitive UI/UX',
    'services.app.features.cloud': 'Cloud Integration',
    'services.integration.title': 'Integrasi Sistem',
    'services.integration.description': 'Mengintegrasikan berbagai sistem bisnis untuk meningkatkan efisiensi dan produktivitas operasional.',
    'services.integration.features.api': 'API Integration',
    'services.integration.features.sync': 'Data Synchronization',
    'services.integration.features.automation': 'Workflow Automation',
    'services.integration.features.monitoring': 'Real-time Monitoring',
    'services.consulting.title': 'Konsultasi IT',
    'services.consulting.description': 'Konsultasi strategis untuk transformasi digital dan optimalisasi infrastruktur teknologi perusahaan.',
    'services.consulting.features.strategy': 'Digital Strategy',
    'services.consulting.features.audit': 'Technology Audit',
    'services.consulting.features.planning': 'Infrastructure Planning',
    'services.consulting.features.training': 'Team Training',
    'services.learnMore': 'Learn More',
    'services.cta.title': 'Siap untuk Transformasi Digital?',
    'services.cta.description': 'Mari diskusikan bagaimana kami dapat membantu mengembangkan solusi teknologi yang tepat untuk kebutuhan bisnis Anda.',
    'services.cta.consultation': 'Konsultasi Gratis',
    'services.cta.portfolio': 'Lihat Portfolio',

    // Portfolio Section
    'portfolio.badge': '🎯 Karya Kami',
    'portfolio.title': 'Portfolio',
    'portfolio.titleHighlight': 'Terbaru',
    'portfolio.titleSuffix': 'Kami',
    'portfolio.subtitle': 'Lihat berbagai proyek yang telah kami selesaikan dengan teknologi terdepan dan standar kualitas tinggi.',
    'portfolio.viewAll': 'Lihat Semua Portfolio',
    'portfolio.projects.migration.title': 'E-Commerce Platform',
    'portfolio.projects.migration.category': 'Web Development',
    'portfolio.projects.migration.description': 'Platform e-commerce lengkap dengan sistem pembayaran terintegrasi dan dashboard admin yang comprehensive.',
    'portfolio.projects.bprmaa.title': 'Healthcare Management App',
    'portfolio.projects.bprmaa.category': 'Mobile Development',
    'portfolio.projects.bprmaa.description': 'Aplikasi mobile untuk manajemen rumah sakit dengan fitur appointment booking dan telemedicine.',
    'portfolio.projects.bprmaainternal.title': 'ERP System Integration',
    'portfolio.projects.bprmaainternal.category': 'System Integration',
    'portfolio.projects.bprmaainternal.description': 'Integrasi sistem ERP dengan berbagai platform eksternal untuk mengoptimalkan workflow perusahaan manufaktur.',
    'portfolio.projects.taskmanagement.title': 'Data Analytics Dashboard',
    'portfolio.projects.taskmanagement.category': 'Data Visualization',
    'portfolio.projects.taskmanagement.description': 'Dashboard analytics real-time untuk monitoring performa bisnis dengan visualisasi data yang interaktif.',
    'portfolio.projects.stock.title': 'IoT Monitoring System',
    'portfolio.projects.stock.category': 'IoT Development',
    'portfolio.projects.stock.description': 'Sistem monitoring IoT untuk smart building dengan sensor terintegrasi dan alert system otomatis.',
    'portfolio.projects.lelang.title': 'Digital Banking App',
    'portfolio.projects.lelang.category': 'Fintech',
    'portfolio.projects.lelang.description': 'Aplikasi mobile banking dengan fitur keamanan tinggi dan user experience yang optimal.',
    'portfolio.projects.zimbra.title': 'E-Learning Platform',
    'portfolio.projects.zimbra.category': 'Web Development',
    'portfolio.projects.zimbra.description': 'Platform e-learning interaktif dengan fitur live classes, quizzes, dan student management system.',
    'portfolio.projects.filesharing.title': 'Social Media App',
    'portfolio.projects.filesharing.category': 'Mobile Development',
    'portfolio.projects.filesharing.description': 'Aplikasi media sosial dengan fitur sharing, messaging, dan community engagement yang inovatif.',
    'portfolio.projects.recruitment.title': 'Real Estate Management System',
    'portfolio.projects.recruitment.category': 'Web Development',
    'portfolio.projects.recruitment.description': 'Sistem manajemen properti real estate dengan fitur listing, booking, dan customer relationship management.',
    'portfolio.projects.disabilities.title': 'Logistics Tracking System',
    'portfolio.projects.disabilities.category': 'Web Development',
    'portfolio.projects.disabilities.description': 'Sistem pelacakan logistik dengan integrasi GPS dan real-time tracking untuk efisiensi pengiriman barang.',
    'portfolio.projects.smk.title': 'SMK 1 Sragi',
    'portfolio.projects.smk.category': 'Web Development',
    'portfolio.projects.smk.description': 'Website profil perusahaan profesional untuk SMK 1 Sragi menampilkan program akademik, prestasi siswa, fasilitas, dan kegiatan sekolah untuk menonjolkan keunggulan pendidikan mereka.',
    'portfolio.projects.roman.title': 'Roman Furniture',
    'portfolio.projects.roman.category': 'Web Development',
    'portfolio.projects.roman.description': 'Website profil perusahaan untuk Roman Furniture yang menampilkan koleksi furnitur premium, layanan desain custom, dan lokasi showroom.',
    'portfolio.projects.roma.title': 'Roma Bangunan',
    'portfolio.projects.roma.category': 'Web Development',
    'portfolio.projects.roma.description': 'Website profil perusahaan untuk Roma Bangunan dengan katalog material bangunan, perlengkapan konstruksi, dan lokasi toko.',
    'portfolio.projects.kpi.title': 'KPI Online BPR MAA',
    'portfolio.projects.kpi.category': 'Web Development',
    'portfolio.projects.kpi.description': 'Sistem indikator kinerja utama online untuk karyawan BPR MAA, menyediakan pelacakan kinerja dan analisis real-time.',
    'portfolio.projects.leave.title': 'Sistem Cuti BPR MAA',
    'portfolio.projects.leave.category': 'Web Development',
    'portfolio.projects.leave.description': 'Sistem pengajuan cuti untuk karyawan BPR MAA, menyediakan proses cuti yang efisien dan mudah.',
    'portfolio.projects.sijitu.title': 'SIJITU - Sistem Pengenalan Wajah',
    'portfolio.projects.sijitu.category': 'Artificial Intelligence',
    'portfolio.projects.sijitu.description': 'SIJITU adalah aplikasi anti pencucian uang berbasis AI untuk verifikasi identitas dan deteksi aktivitas mencurigakan. Salah satu fitur utamanya adalah pengenalan wajah untuk verifikasi identitas otomatis dan akurat.',
    'portfolio.projects.kosman.title': 'Kosman - Sistem Manajemen Kost',
    'portfolio.projects.kosman.category': 'Web Development',
    'portfolio.projects.kosman.description': 'Kosman adalah aplikasi web untuk manajemen properti kost, dengan fitur daftar properti, manajemen penyewa, dan pelacakan pembayaran.',
    'portfolio.projects.barbershop.title': 'Sistem Manajemen Barbershop',
    'portfolio.projects.barbershop.category': 'Web Development',
    'portfolio.projects.barbershop.description': 'Aplikasi web untuk mengelola operasional barbershop dengan fitur penjadwalan, manajemen pelanggan, dan pelacakan layanan.',

    // Testimonials Section
    'testimonials.title': 'Testimoni',
    'testimonials.titleHighlight': 'Klien',
    'testimonials.titleSuffix': 'Kami',
    'testimonials.description': 'Dengarkan langsung dari klien-klien yang telah merasakan manfaat solusi teknologi dari EzProject.',

    'footer.description': 'Memberdayakan bisnis dengan solusi teknologi terkini. Kami berkomitmen menghadirkan inovasi digital yang mendorong pertumbuhan dan transformasi bisnis Anda.',
    'footer.followUs': 'Ikuti Kami',
    'footer.quickContact': 'Kontak Cepat',
    'footer.copyright': '© 2024 EzProject. Semua hak dilindungi.',
    'footer.sections.services': 'Layanan',
    'footer.sections.company': 'Perusahaan',
    'footer.sections.resources': 'Sumber Daya',
    'footer.sections.newsletter': 'Newsletter',
    'footer.newsletter.description': 'Dapatkan update terbaru seputar teknologi dan tips digital.',
    'footer.newsletter.placeholder': 'Email Anda',
    'footer.newsletter.subscribe': 'Langganan',
    'footer.services.website': 'Pembuatan Website',
    'footer.services.mobile': 'Aplikasi Mobile',
    'footer.services.desktop': 'Aplikasi Desktop',
    'footer.services.integration': 'Integrasi Sistem',
    'footer.services.consulting': 'Konsultasi IT',
    'footer.services.iot': 'Produk Internet of Things',
    'footer.services.ai': 'Sistem Artificial Intelligence',
    'footer.company.about': 'Tentang Kami',
    'footer.company.team': 'Tim',
    'footer.company.career': 'Karir',
    'footer.company.blog': 'Blog',
    'footer.company.contact': 'Kontak',
    'footer.resources.portfolio': 'Portfolio',
    'footer.resources.caseStudies': 'Studi Kasus',
    'footer.resources.documentation': 'Dokumentasi',
    'footer.resources.support': 'Dukungan',
    'footer.resources.faq': 'FAQ',
    'footer.legal.privacy': 'Kebijakan Privasi',
    'footer.legal.terms': 'Syarat & Ketentuan',
    'footer.legal.cookie': 'Kebijakan Cookie',
    'footer.legal.sla': 'Perjanjian SLA',

    // Contact Section
    'contact.badge': '📞 Hubungi Kami',
    'contact.title': 'Hubungi',
    'contact.titleHighlight': 'Kami',
    'contact.subtitle': 'Siap memulai proyek teknologi Anda? Hubungi kami untuk konsultasi gratis dan diskusikan kebutuhan bisnis Anda.',
    'contact.info.title': 'Informasi Kontak',
    'contact.info.address.title': 'Alamat Kami',
    'contact.info.address.description': 'Jl. Teknologi No. 123, Jakarta Selatan 12345',
    'contact.info.phone.title': 'Telepon',
    // 'contact.info.phone.description': '+62 21 1234 5678',
    'contact.info.email.title': 'Email',
    'contact.info.email.description': 'cs@ezproject.tech',
    'contact.info.hours.title': 'Jam Operasional',
    'contact.info.hours.description': 'Senin - Jumat: 09:00 - 20:00',
    'contact.services.website': 'Pembuatan Website',
    'contact.services.mobile': 'Pengembangan Aplikasi Mobile',
    'contact.services.system': 'Integrasi Sistem',
    'contact.services.consulting': 'Konsultasi IT',
    'contact.services.maintenance': 'Maintenance Sistem',
    'contact.services.other': 'Layanan Lainnya',
    'contact.chat.title': 'Chat Langsung',
    'contact.chat.description': 'Butuh bantuan segera? Chat dengan tim support kami.',
    'contact.chat.button': 'Mulai Chat',
    'contact.chat.whatsappMessage': 'Halo, saya butuh informasi tentang layanan EzProject.',
    'contact.hours.title': 'Jam Operasional',
    'contact.hours.monday': 'Senin',
    'contact.hours.tuesday': 'Selasa',
    'contact.hours.wednesday': 'Rabu',
    'contact.hours.thursday': 'Kamis',
    'contact.hours.friday': 'Jumat',
    'contact.hours.saturday': 'Sabtu',
    'contact.hours.sunday': 'Minggu',
    'contact.hours.weekdays': 'Senin - Jumat',
    'contact.hours.closed': 'Tutup',
    'contact.form.title': 'Konsultasi Gratis',
    'contact.form.name': 'Nama Lengkap',
    'contact.form.namePlaceholder': 'Masukkan nama lengkap Anda',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'Masukkan alamat email Anda',
    'contact.form.company': 'Perusahaan',
    'contact.form.companyPlaceholder': 'Masukkan nama perusahaan Anda',
    'contact.form.phone': 'Nomor Telepon',
    'contact.form.phonePlaceholder': 'Masukkan nomor telepon Anda',
    'contact.form.service': 'Layanan Dibutuhkan',
    'contact.form.servicePlaceholder': 'Pilih layanan yang Anda butuhkan',
    'contact.form.message': 'Pesan',
    'contact.form.messagePlaceholder': 'Deskripsikan proyek atau kebutuhan Anda',
    'contact.form.submit': 'Kirim Pesan',
    'contact.form.sending': 'Mengirim...',
    'contact.form.success': 'Terima kasih! Permintaan konsultasi Anda telah berhasil dikirim.',
    'contact.form.error': 'Maaf, terjadi kesalahan saat mengirim pesan Anda. Silakan coba lagi.',
    'contact.form.serverError': 'Kesalahan koneksi server. Silakan coba lagi nanti.',
    'contact.location.title': 'Lokasi Kantor',
    'contact.location.viewMap': 'Lihat di Google Maps',
    'contact.map.title': 'Lokasi Kami',
    'contact.map.button': 'Lihat di Google Maps',
    'contact.form.buttons.send': 'Kirim Pesan',
    'contact.form.buttons.sending': 'Mengirim...',
    'contact.form.errors.connectionError': 'Kesalahan koneksi. Silakan coba lagi nanti.',
    'contact.services.desktop': 'Aplikasi Desktop',
    'contact.services.integration': 'Integrasi Sistem',

    // Service Detail Section
    'serviceDetail.website.title': 'Pengembangan Website',
    'serviceDetail.website.subtitle': 'Solusi Website Profesional untuk Bisnis Modern',
    'serviceDetail.website.description': 'Kami mengembangkan website responsif dan modern dengan teknologi terdepan untuk meningkatkan presence online bisnis Anda.',
    'serviceDetail.website.features.responsive': 'Desain Responsif',
    'serviceDetail.website.features.seo': 'SEO Optimized',
    'serviceDetail.website.features.fast': 'Loading Cepat',
    'serviceDetail.website.features.secure': 'Aman & Terpercaya',
    'serviceDetail.website.features.cms': 'Content Management System',
    'serviceDetail.website.features.ecommerce': 'Integrasi E-commerce',
    'serviceDetail.website.features.analytics': 'Integrasi Analytics',
    'serviceDetail.website.features.social': 'Integrasi Media Sosial',
    'serviceDetail.website.benefits.credibility': 'Meningkatkan kredibilitas bisnis',
    'serviceDetail.website.benefits.reach': 'Menjangkau pasar lebih luas',
    'serviceDetail.website.benefits.automation': 'Otomatisasi proses bisnis',
    'serviceDetail.website.benefits.analytics': 'Analisis performa real-time',
    'serviceDetail.website.process.consultation': 'Konsultasi & Analisis Kebutuhan',
    'serviceDetail.website.process.design': 'Desain UI/UX',
    'serviceDetail.website.process.development': 'Pengembangan & Testing',
    'serviceDetail.website.process.launch': 'Peluncuran & Maintenance',
    'serviceDetail.website.pricing': 'Mulai dari Rp50.000.000',
    'serviceDetail.website.timeline': '2-6 minggu',
    'serviceDetail.app.title': 'Pengembangan Aplikasi',
    'serviceDetail.app.subtitle': 'Aplikasi Mobile & Desktop yang Powerful',
    'serviceDetail.app.description': 'Kami mengembangkan aplikasi mobile dan desktop yang user-friendly dengan performa tinggi untuk semua platform. Dari aplikasi mobile native hingga solusi cross-platform, kami menciptakan aplikasi yang memberikan pengalaman pengguna optimal.',

  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language setting from localStorage
    const saved = localStorage.getItem('language');
    // Only use saved language if it exists and is valid, otherwise default to English
    if (saved && (saved === 'en' || saved === 'id')) {
      return saved as Language;
    }
    // Always default to English
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};